"""Renders the public bug investigation report.

Only fields that are safe to show reach this module: no private reasoning, no
secrets, no raw prompts.
"""

from __future__ import annotations

from typing import Any, Dict, List

STATUS_ICON = {
    "PASSED": "PASS",
    "WARNING": "WARN",
    "FAILED": "FAIL",
    "SKIPPED": "SKIP",
}


def _bullets(items: List[Any], empty: str = "_None recorded._") -> str:
    clean = [str(i).strip() for i in (items or []) if str(i).strip()]
    return "\n".join(f"- {item}" for item in clean) if clean else empty


def render_report(state: Dict[str, Any]) -> str:
    debug = state.get("debug_analysis") or {}
    root = state.get("root_cause") or {}
    fix = state.get("proposed_fix") or {}
    review = state.get("review_result") or {}
    validation = state.get("validation_result") or {}
    citations = state.get("citations") or []

    confidence = float(state.get("confidence") or 0.0)
    decision = review.get("decision", "NOT REVIEWED")
    review_mark = "APPROVED" if decision == "APPROVED" else "REJECTED"

    lines: List[str] = [
        "# Bug Investigation Report",
        "",
        f"**Error type:** {debug.get('error_type', 'Unknown')}  ",
        f"**Severity:** {str(debug.get('severity', 'major')).upper()}  ",
        f"**Status:** {str(state.get('status', 'completed')).upper()}",
        "",
        "## Root cause",
        root.get("root_cause") or "_Not determined._",
        "",
        f"**Confidence:** {confidence:.0%}",
        "",
    ]

    if root.get("reasoning_summary"):
        lines += ["### Why", root["reasoning_summary"], ""]

    lines += ["### Evidence", _bullets(root.get("evidence"), "_No evidence was retrieved._"), ""]

    if root.get("alternative_hypotheses"):
        lines += ["### Alternatives considered", _bullets(root["alternative_hypotheses"]), ""]

    lines += ["## Recommended fix", fix.get("recommended_fix") or fix.get("explanation") or "_No fix produced._", ""]

    if fix.get("explanation") and fix.get("recommended_fix"):
        lines += [fix["explanation"], ""]

    if fix.get("patch"):
        lines += ["### Patch", "```diff", fix["patch"].strip(), "```", ""]

    if fix.get("dependency_changes"):
        lines += ["### Dependency changes", _bullets(fix["dependency_changes"]), ""]
    if fix.get("configuration_changes"):
        lines += ["### Configuration changes", _bullets(fix["configuration_changes"]), ""]
    if fix.get("migration_steps"):
        lines += ["### Migration steps", _bullets(fix["migration_steps"]), ""]
    if fix.get("alternative_fix"):
        lines += ["### Alternative approach", str(fix["alternative_fix"]), ""]

    lines += [
        "## Code review",
        f"**{review_mark}** — score {review.get('score', 0)}/100, "
        f"regression risk {review.get('regression_risk', 'MEDIUM')}",
        "",
        review.get("summary", ""),
        "",
    ]
    if review.get("required_changes"):
        lines += ["**Required changes**", _bullets(review["required_changes"]), ""]
    if review.get("recommendations"):
        lines += ["**Recommendations**", _bullets(review["recommendations"]), ""]

    lines += ["## Validation", f"**{validation.get('status', 'SKIPPED')}** — {validation.get('summary', '')}", ""]
    for check in validation.get("checks", []):
        mark = STATUS_ICON.get(check.get("status", "SKIPPED"), "SKIP")
        lines.append(f"- `{mark}` **{check.get('name')}** — {check.get('detail')}")
    lines.append("")

    lines += [f"## Risk", f"**{fix.get('risk', 'MEDIUM')}**", ""]

    if citations:
        lines += ["## Sources"]
        for c in citations:
            lines.append(f"{c['index']}. [{c['title']}]({c['url']}) — _{c['source_type']}_")
        lines.append("")

    if state.get("warnings"):
        lines += ["## Notes", _bullets(state["warnings"]), ""]

    lines += [
        "---",
        "_Generated by BugHound. Static validation only: no user code was executed._",
    ]
    return "\n".join(lines)
